== Guia de Estudo - Semana 1

:cap: cap1
:img: images/{cap}
:online: {gitrepo}/blob/master/livro/code/{cap}
:local: code/{cap}

.Objetivos do capítulo
____
Ao final desta semana você deverá ser capaz de:

*Entender* o que é design instrucional (DI), *resumindo* o seu propósito.

*Entender* a relação do designer e os autores, *classificando* quais
tarefas são do designer e quais dos autores.

*Lembrar* do modelo ADDIE de produção, *reconhecendo* suas etapas e
*identificando* os produtos das etapas de Análise e Planejamento.

*Lembrar* o que é ODL (Open Distance Learning), *reconhecendo* a
definição de ODL e *reproduzindo* a terminologia adotada no livro.

*Criar* o perfil do aluno do nosso curso, *produzindo* o perfil do
aluno que você tomará como base para produção do seu material.

*Analisar* os tipos de terias de aprendizagem, *concluindo* em que
condições cada uma delas seria melhor empregada. 

*Entender* os tipos de design instrucional, *exemplificando* a relação
delas com as teorias de aprendizagem.

*Lembrar* a diferença entre livros tradicionais e livros para ODL,
*reproduzindo* a diferença entre eles e *listando* alguns
dispositivos de instrução (_Embedded devices_).

*Lembrar* do fluxo de decisão de criar ou adaptar um material
existente, *reconhecendo* o fluxo e os dispositivos utilizados na
adaptação.

____

.Organização prévia
****
Durante a leitura deste capítulo será solicito que realize 
algumas atividades, preparamos duas alternativas para realizá-las:

No computador:: Se você optar por responder as atividades escrevendo
no computador então você deverá baixar acessar o caderno digital da
semana, copiar o conteúdo e salvá-lo no editor de texto que escolher. 
Faça isso agora, acesse 

No papel:: 



****

include::s1-ob1-design-instrucional-definicao.adoc[]

O que é design instrucional?
Design instrucional é um processo, técnica ou uma profissão?
Qual o propósito do Design instrucional?



Modelo de produção que adotaremos: ADDIE.




Nós utilizaremos um processo de produção conhecido na literatura como ADDIE,
que possui 5 etapas:

- Análise
- Planejamento
- Desenvolvimento
- Implantação
- Validação

