=== Designer Instrucional para ODL

////
*Entender* a relação do designer e os autores e *lembrar* o que é ODL 
(Open Distance Learning), *classificando* quais
tarefas são do designer e quais dos autores, *reconhecendo* a
definição de ODL e *reproduzindo* a terminologia adotada no livro.

.Organização prévia

- caderno digital
////

==== Introdução

.Questões a serem respondidas
****
. O que é Open Distance Learning (ODL)?
. Como funciona o Open Distance Learning (ODL)?
. Qual a terminologia que utilizaremos no curso?
. Qual a relação entre ODL e os professores do nosso curso?
. Qual o propósito do Design Instrucional para os professores de EAD?
****

==== Open Distance Learning (ODL): o que é?

Uma das principais fontes de estudo que utilizaremos é o livro:
_Creating learning materials for open and distance learning: A Handbook
for Authors and Instructional Designers_. Este livro{empty}footnote:[Este 
livro ensina como realizar o design instrucional de cursos,
mesmo quando não há internet ou energia disponível para os alunos -- 
que são as condições de diversas comunidades na áfrica.] foi produzido pela 
_Commonwealth of Learning_ (http://www.col.org) que tem parceria com
a UNESCO para contribuir com a educação no mundo.


[WARNING]
.Wrap
====
As páginas seguintes apresentam um trecho do livro que explica:

ODL:: 
O que é ODL e sua filosofia.

Terminologia:: Neste trecho será apresentado a terminologia utilizada
no livro, ela é essencial para que possamos compreender o seu conteúdo
com mais precisão. Ter atenção às diferenças entres _Learner_ e _Student_,
entre _Learning aim_ e _Learning objective/outcome_ e ao termo *Wrap-round materials*.

====

++++
<remark>Wrap ODL
    páginas: D1 D10-11
</remark>
++++

<<<

[[atividade_odl_terminologia]]
==== Atividade: Terminologia do livro

image::images/patividade.pdf[]

Registre na tabela seguinte o seu entendimento sobre a terminologia
que foi adotada no livro:

.Terminologia
[cols="1,3a", options="header"]
|====
| Terminologia | Seu entendimento
| Diferença entre _Learner_ e _Student_:
| 
| Diferença entre _Learning aim_ e _Learning objective/outcome_:
| 
| O que seria _Wrap-round materials_:
| 
|====

==== Relação de ODL com nosso material didático

(((ODL, UAB)))

Todo o material didático produzido pela rede UAB pode ser utilizado
pelas instituições de seu rede. Inclusive algumas de nossas disciplinas
utilizam o material produzido por outras instituições.

Atualmente nosso curso é pioneiro, pois também disponibilizamos todo 
o conteúdo na internet para qualquer pessoal baixar.

O material que você produzir também será disponibilizado desta forma.

TIP: Lembre-se que você todos somos beneficiados pela abertura do material 
didático, você poderá selecionar os materiais abertos para inclusão
no design da sua disciplina.

==== Propósito do Design Instrucional para os professores de EAD

O design instrucional para EAD permite planejar a otimização dos 
recursos para possibilitar que seus alunos tenham sucesso na sala
de aula virtual de sua disciplina.

==== Designer Instrucional, Professores e Autores

(((Designer Instruciona))) (((Professor))) (((Autor)))

O *designer instrucional* é um profissional cujo o escopo de suas 
atribuições ultrapassa os limites de uma disciplina.

Durante a leitura dos textos podemos perceber que muitas das 
atribuições do Designer Instrucional poderia ser interpretadas como 
sendo do professor, tais como: planejar atividades, avaliações, 
material didático, etc.

Para simplificar você pode imaginar como o professor sendo um 
especialista no conteúdo e o Designer Instrucional como sendo
um especialista em educação e comunicação. Desta forma, teremos dois 
especialistas trabalhando juntos para otimizar o aprendizado dos 
alunos. Esta relação ficará mais clara nos slides mais aditante.

Quando lemos trechos do livro adotado, também é fácil confundir os
papeis do designer com o do autor/professor conteudista. Mas ele 
deixou claro no início do livro que ele assume o Designer Instrucional
como também sendo o autor do conteúdo:

[quote]
"For simplicity, this handbook addresses primarily the first 
approach -- that in which a single writer is both content-provider 
and instructional designer."

Como professor, você está sendo capacitado a incorporar as técnicas 
de design instrucional em sua disciplina.

[WARNING]
.Wrap
====
As próximas páginas são inclusão de material didático, ter atenção
aos seguintes pontos:

* Atribuições do Designer Instrucional;
* Problemas que podem surgir quando o designer instrucional e os 
autores estão trabalhando juntos e as estratégias para solucioná-los;
 
====


++++
<remark>Wrap
designer instrucional
    páginas: B38-40 B42-43 B45-53 D9 D46-48
</remark>
++++

<<<

[[atividade_designer_autores]]
==== Atividade: Resolução de problemas entre designer instrucional e autores

image::images/patividade.pdf[]

Agora que você conhece um pouco mais o trabalho do Designer Instrucional, 
*liste* pelo menos três atribuições dele que você teria dificuldades 
(ou menos afinidade) em realizar sozinho(a):

image::images/caixa6cm.pdf[]

Você reconhece a necessidade de um Designer Instrucional na equipe 
de um curso a distância? Marque com um &#x2718; na opção que melhor
descreve o seu pensamento:

- [ ] Não, os professores já fazem isto informalmente.
- [ ] Não, os professores podem ser capacitados e incorporar estas funções.
- [ ] Não, estas funções não são essenciais em um curso a distância.
- [ ] Sim, é necessário.

O curso em que você trabalha possui um Designer Instrucional?

- [ ] Não
- [ ] Sim. Quem é? `____________________________`

NOTE: Não há resposta certa ou errada aqui. Estes questionamentos 
estão aqui para possibilitar sua reflexão sobre o papel deste 
profissional na EAD. 

