=== O que é Design Instrucional?

////
*Entender* o que é design instrucional (DI),  *resumindo* o propósito do design instrucional.

.Organização prévia

- caderno digital
////

==== Introdução

Antes de falar sobre Design Instrucional, vamos apreciar o design dos
seguintes objetos:

.Design para apreciação
image::images/cap1/design-pessimo.pdf[]

Como você se sentiria se fosse _obrigado_ a utilizar objetos com
designs semelhantes para realizar as atividades que lhes são atribuídas
normalmente? Que *escolhas* do design dificulta que o objeto seja utilizado
para cumprir o seu *propósito*? Reflita um pouco!

Todo design envolve escolhas que irão influenciar a eficiência da utilização
do objeto para cumprir o propósito para o qual ele foi elaborado. 

Durante os próximos meses estaremos empenhado em auxiliá-lo a realizar
o Design Instrucional da sua disciplina na EAD, dando ênfase no material
didático que será concebido ou adaptado.

.Questões a serem respondidas
****
. Qual o contexto histórico do surgimento do Design Instrucional?
. Quais as definições de Design Instrucional?
****

==== Design Instrucional: história e conceitos

Nas próximas páginas irei fazer um recorte sobre vários materiais
que falam sobre design instrucional.

[WARNING]
.Wrap
====
Gostaria da sua atenção especial para os seguintes pontos:

- Definições de Design Instrucional (ou desenho instrucional);
- Laçamento da *taxonomia dos objetivos educacionais* que ficou
conhecida como *Taxonomia de Bloom* (Na próxima semana, nós 
utilizaremos a atualização desta taxonomia para elaborar nossos objetivos);

====

++++
<remark>Wrap
Entender o que é design instrucional (DI),  resumindo o seu propósito
    páginas: B1-2 B6 B9-17
    C6
</remark>
++++

<<<

[[atividade_di]]
==== Atividade: Entendimento sobre Design Instrucional

image::images/patividade.pdf[]

Agora que você já leu um pouco sobre Design Instrucional, *registre*
o seu entendimento sobre ele.

Para você, o que é Design Instrucional?

image::images/caixa6cm.pdf[]



